# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/webapp/img/kurumi.png', upload_to=''),
        ),
    ]
