# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/img/kurumi.png', upload_to=''),
        ),
    ]
