# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160808_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
